version: '3'

services:

  db:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "ifb_user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "ifb_catalog"
      PGDATA: /var/lib/postgresql/data/pgdata

  web:
    build:
      context: ./
      dockerfile: django.dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
  # The Database manager (adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  # nginx:
  #   build: .
  #   dockerfile: nginx.dockerfile
  #   volumes:
  #     - static_volume:/code/database/static
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

volumes:
  db_data:
  # static_volume:
