# Generated by Django 2.1.2 on 2018-10-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('laboratory', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElixirCommunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.TextField()),
                ('is_tool', models.BooleanField(default=True)),
                ('is_data', models.BooleanField(default=True)),
                ('is_training', models.BooleanField(default=True)),
                ('is_compute', models.BooleanField(default=True)),
                ('is_interoperability', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('communities', models.TextField(default=True)),
                ('date_created', models.DateField(blank=True)),
                ('maturity', models.TextField(choices=[('EMERGING', 'Emerging'), ('MATURE', 'Mature'), ('LEGACY', 'Legacy')], max_length=8)),
                ('access', models.TextField()),
                ('quality', models.TextField()),
                ('usage', models.TextField()),
                ('publication_citations_nb', models.IntegerField()),
                ('publication_coauthor_nb', models.IntegerField()),
                ('tab_user_comittee', models.TextField()),
                ('term_of_use', models.TextField()),
                ('ethics_policy', models.TextField()),
                ('funding', models.TextField()),
                ('motivation_catalog', models.BooleanField(default=True)),
                ('motivation_sdp', models.BooleanField(default=True)),
                ('motivation_support_ifb_it', models.BooleanField(default=True)),
                ('motivation_support_ifb_curation', models.BooleanField(default=True)),
                ('motivation_support_ifb_core_resource', models.BooleanField(default=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Credit')),
                ('elixir_communities', models.ManyToManyField(to='database.ElixirCommunities')),
                ('key_pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Publication')),
            ],
        ),
    ]
