# Generated by Django 2.1.2 on 2018-10-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181025_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tab_user_comittee',
            new_name='sab_user_comittee',
        ),
    ]
