# Generated by Django 2.2 on 2020-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200106_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
