# Generated by Django 2.1.2 on 2018-10-25 16:34

import database.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20181025_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date_created',
        ),
        migrations.AddField(
            model_name='service',
            name='year_created',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1984), database.models.max_value_current_year], verbose_name='year'),
        ),
    ]
