# Generated by Django 2.2 on 2020-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200115_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='downloads',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('MAC', 'Mac')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='software_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='name',
            field=models.CharField(choices=[('Bioinformatics portal', 'Bioinformatics portal'), ('Command-line tool', 'Command-line tool'), ('Database portal', 'Database portal'), ('Desktop application', 'Desktop application'), ('Library', 'Library'), ('Ontology', 'Ontology'), ('Plug-in', 'Plug-in'), ('Script', 'Script'), ('SPARQL endpoint', 'SPARQL endpoint'), ('Suite', 'Suite'), ('Web application', 'Web application'), ('Web API', 'Web API'), ('Web service', 'Web service'), ('Workbench', 'Workbench'), ('Workflow', 'Workflow')], max_length=10000),
        ),
    ]
