# Generated by Django 2.1.2 on 2018-11-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20181025_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elixircommunities',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_compute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_interoperability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_tool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='motivation_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='motivation_sdp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='motivation_support_ifb_core_resource',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='motivation_support_ifb_curation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='motivation_support_ifb_it',
            field=models.BooleanField(default=False),
        ),
    ]
