# Generated by Django 2.2 on 2020-01-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200121_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='downloads',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
