# Generated by Django 2.1.2 on 2018-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20181106_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='credit',
        ),
        migrations.AddField(
            model_name='service',
            name='credit',
            field=models.ManyToManyField(to='database.Credit'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='key_pub',
        ),
        migrations.AddField(
            model_name='service',
            name='key_pub',
            field=models.ManyToManyField(to='database.Publication'),
        ),
    ]
