# Generated by Django 2.1.2 on 2018-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20181106_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='adress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='institute',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='credit',
            name='laboratory',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='credit',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
