# Generated by Django 2.2 on 2020-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_tool_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='otherID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
