# Generated by Django 2.1.2 on 2018-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20181107_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='biotoolsID',
            field=models.TextField(null=True),
        ),
    ]
