# Generated by Django 2.1.2 on 2018-11-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_service_biotoolsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='biotoolsID',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
