# Generated by Django 2.2 on 2020-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_tool_otherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='maturity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
