# Generated by Django 2.1.2 on 2019-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20181128_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='toolType',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
