# Generated by Django 2.1.2 on 2019-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_service_tooltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='toolType',
        ),
        migrations.AddField(
            model_name='service',
            name='toolType',
            field=models.ManyToManyField(to='database.ToolType'),
        ),
    ]
