# Generated by Django 2.2 on 2020-01-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_tool_collectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='credit',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
