# Generated by Django 2.1.2 on 2019-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190115_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='biotoolsID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='elixir_communities',
            field=models.ManyToManyField(blank=True, to='database.ElixirCommunities'),
        ),
        migrations.AlterField(
            model_name='service',
            name='key_pub',
            field=models.ManyToManyField(blank=True, to='database.Publication'),
        ),
    ]
