# Generated by Django 2.2 on 2020-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_tool_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='elixirNode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='elixirPlatform',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
