# Generated by Django 2.2 on 2020-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200121_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='elixirNode',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
