# Generated by Django 2.2 on 2020-01-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200121_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='credit',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='elixirNode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='elixirPlatform',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
