# Generated by Django 2.2 on 2020-01-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20200121_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='accessibility',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='cost',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
