# Generated by Django 2.2 on 2020-01-21 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_tool_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltype',
            name='additionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='biotoolsCURIE',
            field=models.CharField(max_length=109),
        ),
        migrations.AlterField(
            model_name='tool',
            name='biotoolsID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='name',
            field=models.CharField(blank=True, choices=[('Bioinformatics portal', 'Bioinformatics portal'), ('Command-line tool', 'Command-line tool'), ('Database portal', 'Database portal'), ('Desktop application', 'Desktop application'), ('Library', 'Library'), ('Ontology', 'Ontology'), ('Plug-in', 'Plug-in'), ('Script', 'Script'), ('SPARQL endpoint', 'SPARQL endpoint'), ('Suite', 'Suite'), ('Web application', 'Web application'), ('Web API', 'Web API'), ('Web service', 'Web service'), ('Workbench', 'Workbench'), ('Workflow', 'Workflow')], max_length=100, null=True),
        ),
    ]
