# Generated by Django 2.2 on 2020-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='language',
        ),
        migrations.AddField(
            model_name='tool',
            name='language',
            field=models.ManyToManyField(blank=True, to='database.Language'),
        ),
    ]
