# Generated by Django 2.2 on 2020-01-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_remove_tool_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='language',
            field=models.ManyToManyField(blank=True, to='database.Language'),
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tool_type',
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolType', to='database.ToolType'),
        ),
    ]
