# Generated by Django 2.2 on 2020-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20200121_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='tool_type',
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.ManyToManyField(blank=True, to='database.ToolType'),
        ),
    ]
