# Generated by Django 2.2 on 2020-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_operatingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pmcid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pmid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='publication',
            field=models.ManyToManyField(blank=True, to='database.Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
