# Generated by Django 2.2 on 2020-01-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20200122_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doawnload',
            new_name='Download',
        ),
    ]
