# Generated by Django 2.2 on 2020-01-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_auto_20200122_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='relation',
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotoolsID', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('additionDate', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='database.Tool')),
            ],
        ),
    ]
