# Generated by Django 2.2 on 2020-01-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20200123_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('additionDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='collectionID',
        ),
        migrations.AddField(
            model_name='tool',
            name='collection',
            field=models.ManyToManyField(blank=True, to='database.Collection'),
        ),
    ]
