# Generated by Django 2.2 on 2020-01-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20200123_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='software_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
