# Generated by Django 2.2 on 2020-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20200123_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('orcidid', models.CharField(blank=True, max_length=100, null=True)),
                ('gridid', models.CharField(blank=True, max_length=100, null=True)),
                ('typeEntity', models.CharField(blank=True, max_length=100, null=True)),
                ('typeRole', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='toolCredit',
            field=models.ManyToManyField(blank=True, to='database.ToolCredit'),
        ),
    ]
