# Generated by Django 3.0.3 on 2020-02-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_auto_20200131_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='credit',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
