# Generated by Django 3.0.3 on 2020-02-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
