# Generated by Django 3.0.3 on 2020-02-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_auto_20200212_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='tool_id',
            new_name='tool',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='tool_id',
            new_name='tool',
        ),
    ]
