# Generated by Django 3.0.3 on 2020-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_data_format_input_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='function',
        ),
        migrations.AddField(
            model_name='function',
            name='operation',
            field=models.ManyToManyField(blank=True, to='database.Operation'),
        ),
    ]
