# Generated by Django 3.0.3 on 2020-02-13 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0060_auto_20200213_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='additionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='database.Tool'),
        ),
    ]
