# Generated by Django 3.0.3 on 2020-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_auto_20200213_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='cmd',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
