# Generated by Django 3.0.3 on 2020-03-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_auto_20200214_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
