# Generated by Django 3.0.4 on 2020-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_auto_20200311_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationauthor',
            name='metadata',
        ),
        migrations.AddField(
            model_name='publicationmetadata',
            name='publicationAuthor',
            field=models.ManyToManyField(blank=True, to='database.PublicationAuthor'),
        ),
    ]
