# Generated by Django 3.0.4 on 2020-03-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_documentation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='resource',
            new_name='tool',
        ),
    ]
